[project]
name = "skyweaver"
version = "0.1.0"
description = "A modular simulator to organize airspace constraints and orchestrate future autonomous aerial operations."
authors = [
    {name = "DaviGuanabara",email = "davi_guanabara@live.com"}
]

readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.3.0,<3.0.0)",
    "numpy (>=2.3.1,<3.0.0)",
    "geopandas (>=1.1.1,<2.0.0)",
    "shapely (>=2.1.1,<3.0.0)",
    "gymnasium (>=1.2.0,<2.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "rastreio (>=0.0.3,<0.0.4)",
    "rasterio (>=1.4.3,<2.0.0)",
    "pyswarm (>=0.6,<0.7)",
    "scipy (>=1.16.1,<2.0.0)",
    "plotly (>=6.3.1,<7.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
    "hdbscan (>=0.8.40,<0.9.0)",
    "alphashape (>=1.3.1,<2.0.0)",
    "anywidget (>=0.9.18,<0.10.0)",
    "streamlit (>=1.51.0,<2.0.0)",
    "cma (>=4.4.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
packages = [
    { include = "skyweaver", from = "src" }
]
